#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.
#
# 03-03-2013: Jose R Rodriguez/Metztli IT http://www.metztli-it.com
# Due diligence has been exercised but no guarantees are conveyed in either
# explicit or implicit manner or form.
#
if  [ -L  $OPENSHIFT_REPO_DIR/php/cache ]
then
exit
else
	if [ -d $OPENSHIFT_REPO_DIR/php/cache ] && [ -d $OPENSHIFT_DATA_DIR/cache ]
	then
	rm -rf $OPENSHIFT_REPO_DIR/php/cache
	ln -s $OPENSHIFT_DATA_DIR/cache $OPENSHIFT_REPO_DIR/php/cache
	else
	mv -f $OPENSHIFT_REPO_DIR/php/cache $OPENSHIFT_DATA_DIR/.
	ln -s $OPENSHIFT_DATA_DIR/cache $OPENSHIFT_REPO_DIR/php/cache
	exit
	fi
exit
fi
